#define FLOW_TAP_TERM 100
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 90

#define SERIAL_NUMBER "lJwr0/DzqL57"
#define LAYER_STATE_8BIT

#define TAPPING_TERM_PER_KEY
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 0
#define MOUSE_EXTENDED_REPORT
#define WHEEL_EXTENDED_REPORT
#define NAVIGATOR_TRACKBALL_CPI 20
#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 3
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

